"""Execution task and stage category names."""

from __future__ import annotations

from enum import Enum


class TaskType(str, Enum):
    """Known execution categories used by planners and validators."""

    ASSET_CONFIRMATION = "ASSET_CONFIRMATION"
    PORT_SCAN = "PORT_SCAN"
    SERVICE_VALIDATION = "SERVICE_VALIDATION"
    INTERNAL_SERVICE_FINGERPRINT = "INTERNAL_SERVICE_FINGERPRINT"
    WEB_ENUMERATION = "WEB_ENUMERATION"
    WEB_DISCOVERY = "WEB_DISCOVERY"
    VULNERABILITY_VALIDATION = "VULNERABILITY_VALIDATION"
    CREDENTIAL_VALIDATION = "CREDENTIAL_VALIDATION"
    CREDENTIAL_REUSE_VALIDATION = "CREDENTIAL_REUSE_VALIDATION"
    REACHABILITY_VALIDATION = "REACHABILITY_VALIDATION"
    LATERAL_REACHABILITY_VALIDATION = "LATERAL_REACHABILITY_VALIDATION"
    IDENTITY_CONTEXT_CONFIRMATION = "IDENTITY_CONTEXT_CONFIRMATION"
    PRIVILEGE_CONFIGURATION_VALIDATION = "PRIVILEGE_CONFIGURATION_VALIDATION"
    GOAL_CONDITION_VALIDATION = "GOAL_CONDITION_VALIDATION"
    EVIDENCE_COLLECTION_AND_ARCHIVAL = "EVIDENCE_COLLECTION_AND_ARCHIVAL"
    RECON_STAGE = "RECON_STAGE"
    VULN_ANALYSIS_STAGE = "VULN_ANALYSIS_STAGE"
    EXPLOIT_STAGE = "EXPLOIT_STAGE"
    ACCESS_PIVOT_STAGE = "ACCESS_PIVOT_STAGE"
    GOAL_STAGE = "GOAL_STAGE"


__all__ = ["TaskType"]
